### ISSUE TITLE
NullPointerException in Fetcher.java

### ISSUE THREAD

**Issue by ehiggs** [Seagate/hadoop-on-lustre2#1]
Hi, thanks for releasing this code. It looks like it will be very useful for those of us running Hadoop on traditional HPC systems.

I tried out the TeraSortLustre benchmark and ran into a null pointer exception in Fetcher.java:

```
2014-12-16 17:04:08,476 INFO  [main] mapreduce.Job (Job.java:printTaskEvents(1441)) - Task Id : attempt_1418745390618_0001_r_000039_1, Status : FAILED
Error: org.apache.hadoop.mapreduce.task.reduce.Shuffle$ShuffleError: error in shuffle in fetcher#1
        at org.apache.hadoop.mapreduce.task.reduce.Shuffle.run(Shuffle.java:134)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:376)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:167)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)
Caused by: java.lang.NullPointerException
        at org.apache.hadoop.mapreduce.task.reduce.Fetcher.copyMapOutput(Fetcher.java:411)
        at org.apache.hadoop.mapreduce.task.reduce.Fetcher.copyFromHost(Fetcher.java:278)
        at org.apache.hadoop.mapreduce.task.reduce.Fetcher.run(Fetcher.java:177)

Container killed by the ApplicationMaster.
Container killed on request. Exit code is 143
```

I looked at Fetcher.java in the hadoop-on-lustre2 code and I see that the apache trunk at the time had [this code](https://github.com/Seagate/hadoop-on-lustre2/blob/master/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/Fetcher.java#L278):

```
 while (!remaining.isEmpty() && failedTasks == null) {
    //failedTasks = copyMapOutput(host, input, remaining);
    failedTasks = copyMapOutput(host, null, remaining);
}
```

I suppose passing null here would be a good place to begin investigating.

I compared it with the current trunk on apache and it looks like [the apache trunk changed dramatically.](https://github.com/apache/hadoop-common/blob/trunk/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/task/reduce/Fetcher.java#L265):

```
try {
    URL url = getMapOutputURL(host, maps);
    openConnection(url);
    if (stopped) {
        abortConnect(host, remaining);
        return;
    }
...
```

So, I suppose the issue is of two parts: have you seen this error? Maybe it's due to a misconfiguration? If not, would it be best to rebase this code?

Thanks!

**Comment by ehiggs** [comment]
Hi Stephen,

FWIW, we're using GPFS. Going through the code I didn't see anything that was Lustre specific, so I I thought it might work on other parallel file systems (Lustre, GPFS, Panasas, etc.). I mean, it looks like it's using links within the file system to handle the fact that the results of the map phase are almost instantly copied across nodes. It doesn't seem particularly unique to Lustre.

>Also, do you have any other versions of Hadoop2 installed on this particular system/cluster?

We're using the [module system](http://www.uky.edu/ukit/hpc/docs/module) to manage several Hadoop installs. This is a commonly used piece of kit in HPC. The ones from Cloudera all work.

>Can you share your configuration, just to double check?

Sure. I put it in pastebin [here](http://pastebin.com/TU2Rv7Qp).

**Comment by ehiggs** [comment]
Hi Stephen,
I got this working on GPFS. It turns out I had to build the native hadoop libraries (`libhadoop.so`) so the `ReadAheadPool` singleton returns an actual object. I guess they don't throw there since it would mean everyone would need to check exceptions to access the singleton. Perhaps a `LOG.error` would be better.
